# Generated by Django 5.1.4 on 2024-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='file',
            field=models.FileField(upload_to='knowledge_base/'),
        ),
    ]
